version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: lua-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - lua-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  lua-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lua-backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - REDIS_URL=redis://redis:6379
      - DATABASE_URL=sqlite:///app/data/lua_system.db
      - API_HOST=0.0.0.0
      - API_PORT=8000
      - USE_GPU=false
      - LOG_LEVEL=INFO
    volumes:
      - ./backend:/app/backend
      - ./frontend:/app/frontend
      - ./data:/app/data
      - ./models:/app/models
      - ./output:/app/output
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - lua-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  redis_data:
  
networks:
  lua-network:
    driver: bridge